### ISSUE TITLE
Provide a toggle button on the menu bar to toggle dark mode

### ISSUE THREAD

**Issue by vivekweb2013** [batnoter/batnoter#76]
Currently the dark mode is applied only if it is set for the operating system or browser.
I think there should be an application specific toggle button which will allow users to turn on/off dark mode.

By default the toggle mode should be initialised as per the system setting. i.e. if the system/browser is set to light/dark mode then toggle button should be initialised with the same mode. But when user clicks it should toggle the mode.

Also update the readme and include the dark mode feature in the features list 😄

**Comment by vivekweb2013** [comment]
Done ✅

**Comment by spartan4cs** [comment]
Thanks
