### ISSUE TITLE
404 image is not showing for nested paths

### ISSUE THREAD

**Issue by vivekweb2013** [batnoter/batnoter#77]
**Describe the bug**
The png graphic is showing correctly for 404 route only for the first level path. i.e `https://batnoter.com/abc` but it is not showing up for nested path i.e. `https://batnoter.com/abc/xyz`

**Screenshots**
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/7036736/173237910-e48b7db1-6c60-4bee-a674-3f21de709da8.png">

**Comment by shikhar13012001** [comment]
Hi @vivekweb2013 I would like to work on this issue, sorry I have had previous academic related issues going on for a while.

**Comment by vivekweb2013** [comment]
sure @shikhar13012001 

Let me share my analysis. It looks like it is only happening on the github pages not sure why. On local setup the image is showing properly even for the nested paths

**Comment by shikhar13012001** [comment]
May be changing the image path to web url should fix this issue. https://i.ibb.co/wprRPLF/404.png

**Comment by vivekweb2013** [comment]
@shikhar13012001 that would not be a nice fix. I'd like the resources to be served from same site rather than using external site urls. Since it will introduce a dependency on this external site

**Comment by shikhar13012001** [comment]
okay I understand, I will try to work on this issue.

**Comment by shikhar13012001** [comment]
hmm.. It seems like path is actually ```../static/images/404...png```, But I still don't know why is this happening.

**Comment by vivekweb2013** [comment]
@shikhar13012001 yeah this is strange

**Comment by shikhar13012001** [comment]
@vivekweb2013  Did you find a solution to it? I think the raw github url is only possibility here :(

**Comment by vivekweb2013** [comment]
@shikhar13012001 I did not get enough time to look at this issue but for now I think we can place the 404 image in `public/images` directory and hardcode the absolute root path i.e. `/images/404.png`

I think this will work because of the absolute path. So we can make these changes for now

**Comment by vivekweb2013** [comment]
@shikhar13012001 seems like the issue was cased by `homepage: "."` property set in `package.json` file. Removing it fixed the issue.

**Comment by shikhar13012001** [comment]
> @shikhar13012001 seems like the issue was cased by `homepage: "."` property set in `package.json` file. Removing it fixed the issue.

Ohh thanks!! I didn't notice this.

**Comment by vivekweb2013** [comment]
Fixed
