### ISSUE TITLE
Hide the menu bar labels on smaller screen resolutions

### ISSUE THREAD

**Issue by vivekweb2013** [batnoter/batnoter#80]
On smaller screens (resolution < 900px) 
- [x] The labels of the links present on menu bar should be hidden

Helpful links:
- https://mui.com/system/display/#hiding-elements
- https://mui.com/material-ui/customization/breakpoints/#default-breakpoints

**Comment by nerdjfpb** [comment]
Hi @vivekweb2013 I'm new to this codebase, but I'm interested to take this. 

Can you assign this to me?

Thanks!

**Comment by vivekweb2013** [comment]
Hi @nerdjfpb Sure 👍

**Comment by nerdjfpb** [comment]
![Mobile view](https://user-images.githubusercontent.com/47062625/173249130-1664c356-4866-4a72-b1d9-15d720cb7ffb.png)

Is this looking good? Do I need to change the login part too? @vivekweb2013

**Comment by vivekweb2013** [comment]
@nerdjfpb this looks good to me 👍 Do apply this change to login button.

BTW there is one more link `create note` that is visible on login. Please check if its included in this change.
