### ISSUE TITLE
Add .nvmrc to ensure correct node version is used

### ISSUE THREAD

**Issue by WilsonLe** [batnoter/batnoter#98]
This is not a problem, just an enchancement for future contributors. The README specifies to use Node18 or above. We can programatically ensure that future contributor is always using the correct Node version.

I would like to add a `.nvmrc` file for future contributor to match this Node version just by using `nvm use` (assuming they use nvm for Node)

**Comment by vivekweb2013** [comment]
@WilsonLe Thats a good idea. Please raise a PR for this.
